spring.application.name=investment-portfolio-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=portfolio_user
spring.datasource.password=portfolio_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=rg.hibernate.dialect.PostgreSQLDialect

market-data.alpha-vantage.base-url=https://www.alphavantage.co/query
market-data.alpha-vantage.api-key=XXXXXXXXXXXXXXXXX
